name: volunteer_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.7.0

  # Secure token storage
  flutter_secure_storage: ^9.2.2

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.6.2


  # Dates
  intl: ^0.19.0
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
